name: "My first CI test"
on:

  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
      java-version: '12.x'
    - uses: subosito/flutter-actions@v2
      with:
      flutter-version: '3.x.x'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: "Push to release"
      uses: ncipollo/release-action@v1
      with:
        artifact: "build/app/apk/debug/*"
        tag: v1.0.$({ github.run_number})



# push main
# pull request on main
